export const AppLabels = {
    txt_Employee : 'Employee ID',
    txt_Password : 'Password',
    txt_Filter : 'Filter',
    txt_Nodata : 'No data available',
    txt_EmpCode : 'Employee Code',
    txt_FirstName : 'First Name',
    txt_Email : 'Email',
    txt_Mobile  : 'Mobile',
    txt_EmpStatus :'Employment Status',
    txt_BankPartner:'Bank Partner',
    txt_Department:'Department',
    txt_Designation:'Designation',
    txt_State:'State',
    txt_Area:'Area',
    txt_Branch:'Branch',
    txt_Role:'Role',
    txt_LeavingDate:'Date of Leaving',
    txt_JoiningDate:'Date of Joining',
     txt_IsActive:'Is Active',
     txt_CourseName :'Course Name',
     txt_General :'General',
     txt_assessmentName :'Assessment Name',
     txt_QuestionPaper :'Question Paper',
     txt_DurationIn :'Duration In',
     txt_Duration :'Duration',
     txt_QuestionsNo :'Number Of Questions',
     txt_TotalMarks :'Total Marks',
     txt_PassingMarks :'Passing Marks',
     txt_AttemptsNo :'Number Of Attempts',
     txt_QuestionTitle :'Question Title',
     txt_QuesExcel :' Question Upload Excel',
     txt_FromDate : 'From Date',
     txt_ToDate : 'To Date',
     txt_Bank : 'Bank', 
     txt_EmployeeGroup  : 'Employee Group',
     txt_Show:'Show',
     txt_SelectItems: 'Select Items per Page',
     txt_entries:'entries',
     txt_area :'Area',
     txt_EmployeeName :'Employee',
     txt_Completed :'Completed',
     txt_Coursesfinished : 'Courses finished successfully' ,
     txt_InProgress :'In Progress',
     txt_Coursesongoing :'Courses currently ongoing',
     txt_Unassigned :'Unassigned',
     txt_Coursesassigned :'Courses yet to be assigned',
     txt_NotStarted :'Not Started',
     txt_Coursesassignednotbegun :'Courses assigned but not begun',
     txt_ProgressTracker :'Course Progress Tracker',
     txt_CertificateType :'Certificate Type',
     txt_Upload :'Upload',
     txt_Certificate :'Certificate',
     txt_EvidenceDetails :'Evidence Details',
     txt_TraineeImage :'Trainee Image',
      txt_TrainerImage :'Trainer Image',
     txt_Showing:'Showing',
     txt_EvidenceDate :'Evidence Upload Date',
     txt_LatLong :'Lat-Long',
     txt_Match:'Match with Trainee and Trainer Image',
     txt_IsMatch :'Match',
     txt_Similarity:'Similarity',
     txt_Showentries:'Show entries'
  };

  export const AppHeader = {
    Header: 'Skill Mate',
    SubHeader : 'Learning Portal Application',
    CourseHeader:'Course Details',
    ChapterHeader:'Chapter Details',
    UserHeader:'User Details',
   AssessmentHeader:'Assessment Details',
    QuestionHeader:'Question Details',
    Reports:'Reports',
    Training:'Training Status'
  };

  export const AppLink = {
    link_forget : 'Forgot password?',
  };

  
  export const AppButton = {
    LoginButton: 'Login',
    submitButton: 'Submit',
    cancelButton: 'Cancel',
    SearchButton: 'Search',
    CourseButton: ' Create Course',
    ChapterButton: ' Create Chapter',
    AddUserButton :'Add User',
    ReportButton :'Report Builder',
    AssessmentButton :' Add Assessment',
    QuestionButton:'Add Question Paper',
    TemplateButton:'Download Template',
    View:'View',
    Download:'Download',
    FaceMatch:'Face Match'
  };

  export const AppPlaceHolder ={
    ph_password :'Enter Your Password',
    ph_EmpID :'Enter Your Employee Id',
    ph_Captcha :'Enter Captcha',
    ph_FirstName :'Enter First Name',
    ph_Email :'Enter Email',
    ph_Mobile :'Enter Mobile',
    ph_EmpStatus :'Enter Employment Status',
    ph_BankPartner :'Enter Bank Partner',
    ph_Department :'Enter Department',
    ph_Designation :'Enter Designation',
    ph_State :'Enter State',
    ph_Area :'Enter Area',
    ph_Branch :'Enter Branch',
    ph_Assessment:"Enter Assessment Name",
    ph_TotalMarks :'Enter Total Marks',
    ph_PassingMarks :'Enter Passing Marks',
    ph_AttemptsNo :'Enter Number Of Attempts',
    ph_QuestionsNo :'Enter no of Questions',
    ph_Duration :'Enter Duration',
  }

  export const Apptable ={
    tbl_SRNo :'SR. No',
    tbl_CourseName :'Course Name',
    tbl_ChapterName :'Chapter Name',
    tbl_Edit :'Edit',
    tbl_Mapping :'Mapping',
    tbl_Delete :'Delete',
    tbl_Action :'Action',
    tbl_Assessment :'Assessment Name',
    tbl_Duration :'Duration',
    tbl_Question:'Question Paper Name',

    tbl_EmpID : 'Employee Code',
     tbl_EmpName :'First Name',
     tbl_Area :'Area',
     tbl_Bank :'Bank',
      tbl_Branch :'Branch',
      tbl_Designation :'Designation',
     tbl_Region :'Region',
     tbl_State :'State',
     tbl_CStart :'Course Start',
     tbl_CExpiry :'Course Expiry',
     tbl_CProgress :'Course Progress',
     tbl_CompletedDate :'Course Completed Date',
     tbl_Status :'Course Status',
    tbl_TestStatus :'Test Status',
    tbl_TestDate :'Test Date',
    tbl_Timestamp :'Test Timestamp',
    tbl_Marks :'Test Marks',
    tbl_ObtainedMarks :'Obtained Marks',
    tbl_PassMarks :'Pass Marks',
    tbl_UploadedCertificate :'Uploaded Certificate',
    tbl_Download :'Download',
    tbl_Type:'Type',
    tbl_dateofJoinning :'Date of Joining',
    tbl_TraineeCode :'Trainee Code',
    tbl_TraineeName :'Trainee Name',
    tbl_TrainerCode :'Trainer Code',
    tbl_TrainerName :'Trainer Name'
  }

